services:
  monitor:
    build: .
    container_name: simple-monitor
    command: ["node", "dist/monitor.js"]
    environment:
      - SCREENSHOT_CRON=*/10 * * * * # every 10 minutes
      - RETENTION_DAYS=2 # keep 2 days of screenshots (1.7GB / day)
    volumes:
      - ./data:/usr/src/app/data
      - ./sitelist.txt:/usr/src/app/sitelist.txt:ro

  web:
    build: .
    container_name: simple-monitor-web
    command: ["node", "dist/server.js"]
    environment:
      - PORT=3000
    depends_on:
      - monitor
    volumes:
      - ./data:/usr/src/app/data:ro
      - ./sitelist.txt:/usr/src/app/sitelist.txt:ro
    ports:
      - "3000:3000"
